apiVersion: v1
kind: Service
metadata:
  name: e-commerce-node-service
spec:
  type: LoadBalancer
  selector:
    app: e-commerce-node
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
